Repository the-young-hana/theYoungHana-backend, pull requests merged in 2024-07, with the labels that each got.

#52 fix: StudentReadResDto 수정
  src/main/java/hana/member/dto/StudentReadResDto.java
  src/main/java/hana/member/service/StudentService.java
Labels: fix

#55 feat: 스토리 좋아요 관련 API 구현 (#54)
  src/main/java/hana/story/controller/StoryController.java
  src/main/java/hana/story/domain/StoryLike.java
  src/main/java/hana/story/domain/StoryLikeRepository.java
  src/main/java/hana/story/dto/StoriesReadResDto.java
  src/main/java/hana/story/dto/StoryCreateLikeResDto.java
  src/main/java/hana/story/dto/StoryReadResDto.java
  src/main/java/hana/story/service/StoryLikeService.java
  src/main/java/hana/story/service/StoryService.java
Labels: feat

#57 chore: 데이터베이스 생성자/수정자 자동화(#56)
  src/main/java/hana/common/config/AuditAwareImpl.java
  src/main/java/hana/common/config/JpaAuditConfig.java
  src/main/java/hana/common/entity/BaseEntity.java
Labels: chore

#58 fix: 입금/출금자 이름 바뀌어서 나오는 버그 수정
  src/main/java/hana/account/service/TransactionService.java
Labels: fix

#59 refactor: 인가 관련 예외처리 추가
  src/main/java/hana/account/controller/TransactionController.java
  src/main/java/hana/account/service/TransactionService.java
  src/main/java/hana/common/exception/AccessDeniedCustomException.java
  src/main/java/hana/common/exception/CommonHttpCode.java
  src/main/java/hana/story/controller/StoryController.java
  src/main/java/hana/story/service/StoryService.java
Labels: refactor

#60 fix: cors 오류 해결
  .github/workflows/ci_and_cd.yml
  .github/workflows/pull_request_test.yml
  src/main/java/hana/common/config/FirebaseConfig.java
  src/main/java/hana/common/config/SecurityConfig.java
  src/main/java/hana/notification/controller/NotificationController.java
Labels: fix

#61 feat: 스토리 댓글 관련 기능 구현
  src/main/java/hana/common/repository/StoreQueryRepository.java
  src/main/java/hana/story/controller/StoryCommentController.java
  src/main/java/hana/story/domain/StoryComment.java
  src/main/java/hana/story/domain/StoryCommentRepository.java
  src/main/java/hana/story/dto/StoryCommentPaginationDto.java
  src/main/java/hana/story/dto/StoryCreateCommentResDto.java
  src/main/java/hana/story/dto/StoryUpdateCommentResDto.java
  src/main/java/hana/story/service/StoryCommentService.java
Labels: feat

#62 feat: 리워드 관련 api 구현
  src/main/java/hana/college/domain/DeptRepository.java
  src/main/java/hana/member/domain/Student.java
  src/main/java/hana/member/domain/StudentRepository.java
  src/main/java/hana/notification/controller/NotificationController.java
  src/main/java/hana/reward/controller/RewardController.java
  src/main/java/hana/reward/service/RewardService.java
Labels: feat

#65 feat: 리워드 내역 추가 및 에러 핸들링
  src/main/java/hana/member/domain/RewardHistory.java
  src/main/java/hana/member/exception/StudentNotFoundException.java
  src/main/java/hana/reward/controller/RewardController.java
  src/main/java/hana/reward/domain/RewardHistory.java
  src/main/java/hana/reward/domain/RewardHistoryCategoryEnumType.java
  src/main/java/hana/reward/domain/RewardHistoryRepository.java
  src/main/java/hana/reward/dto/RewardReadResDto.java
  src/main/java/hana/reward/exception/PresentException.java
  src/main/java/hana/reward/exception/QuizException.java
  src/main/java/hana/reward/exception/RewardHttpCode.java
  src/main/java/hana/reward/service/RewardService.java
Labels: feat

#78 refactor: 회원 간편로그인 API 수정 (FCM 토큰 추가)
  build.gradle
  src/main/java/hana/common/Service/FCMService.java
  src/main/java/hana/common/config/FirebaseConfig.java
  src/main/java/hana/common/config/RedisConfig.java
  src/main/java/hana/common/dto/Notification/FcmMessageResDto.java
  src/main/java/hana/common/dto/Notification/FcmSendReqDto.java
  src/main/java/hana/member/controller/MemberController.java
  src/main/java/hana/member/domain/MemberToken.java
  src/main/java/hana/member/domain/MemberTokenRepository.java
  src/main/java/hana/member/dto/MemberLoginReqDto.java
  src/main/java/hana/member/service/MemberService.java
  src/main/java/hana/member/service/MemberTokenService.java
  src/main/java/hana/notification/controller/NotificationController.java
  src/main/resources/data.sql
  src/test/java/hana/ApplicationTests.java
  src/test/java/hana/common/annotation/MethodInfoTest.java
  src/test/java/hana/common/annotation/TypeInfoTest.java
  src/test/java/hana/common/config/AppTestConfig.java
  src/test/java/hana/common/config/MySQLTestConfig.java
  src/test/java/hana/common/config/RedisTestConfig.java
Labels: refactor

#80 feat: 이벤트 관련 API 구현
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/domain/EventRepository.java
  src/main/java/hana/event/dto/EventCreateResDto.java
  src/main/java/hana/event/dto/EventPushOnResDto.java
  src/main/java/hana/event/dto/EventReadResDto.java
  src/main/java/hana/event/dto/EventUpdateResDto.java
  src/main/java/hana/event/exception/EventHttpCode.java
  src/main/java/hana/event/exception/InProgressEventException.java
  src/main/java/hana/event/service/EventService.java
Labels: feat

#82 :ambulance: FCM 예외처리 수정
  src/main/java/hana/common/Service/FCMService.java
  src/main/java/hana/event/domain/EventPrizeRepository.java
Labels: fix

#83 feat: 좋아요/댓글 수 정합성을 위한 스케줄러 작성 (#48)
  src/main/java/hana/story/service/MatchCountScheduler.java
Labels: feat

#87 refactor: DTO 하나로 통합 및 적용
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/dto/EventCreateResDto.java
  src/main/java/hana/event/dto/EventReadResDto.java
  src/main/java/hana/event/dto/EventUpdateResDto.java
Labels: refactor

#88 refactor: 스토리 목록 조회 리턴값 수정 (#48)
  src/main/java/hana/account/domain/TransactionRepositoryImpl.java
  src/main/java/hana/account/service/TransactionService.java
  src/main/java/hana/story/dto/StoriesReadResDto.java
  src/main/java/hana/story/service/StoryService.java
Labels: refactor

#90 refactor: 이벤트 추가 DTO 수정 (이미지 추가)
  src/main/java/hana/common/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/domain/ScheduledEvent.java
  src/main/java/hana/event/dto/EventCreateReqDto.java
  src/main/java/hana/event/dto/EventReadResDto.java
  src/main/java/hana/event/dto/EventUpdateReqDto.java
Labels: refactor

#92 refact: 학과-계좌 n+1해결
  src/main/java/hana/account/service/TransactionService.java
  src/main/java/hana/college/domain/DeptRepository.java
  src/main/java/hana/college/service/DeptService.java
Labels: refactor

#94 test: 프로메테우스, 그라파나 연동
  docker-compose.yml
  prometheus.yml
Labels: test

#98 refactor: 스토리 상세 조회 리턴값 날짜별로 리턴 (#48)
  src/main/java/hana/account/domain/TransactionRepositoryCustom.java
  src/main/java/hana/account/domain/TransactionRepositoryImpl.java
  src/main/java/hana/account/dto/TransactionsReadResDto.java
  src/main/java/hana/account/service/TransactionService.java
  src/main/java/hana/story/dto/StoryReadResDto.java
  src/main/java/hana/story/service/StoryService.java
Labels: refactor

#99 fix: 이벤트 수정 시 이미지 관련 오류 수정
  src/main/java/hana/common/utils/ImageUtils.java
  src/main/java/hana/event/controller/EventController.java
Labels: fix

#101 refactor: 이벤트 API에 최초생성일시 정보 추가
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/dto/EventReadResDto.java
  src/main/java/hana/event/dto/EventsReadResDto.java
Labels: refactor

#102 금융상식 목록 조회 페이지네이션 기능 추가
  src/main/java/hana/knowledge/controller/KnowledgeController.java
  src/main/java/hana/knowledge/dto/KnowledgePaginationDto.java
  src/main/java/hana/knowledge/service/KnowledgeService.java
Labels: feat

#103 fix: 이벤트 수정 시 이미지 관련 오류 수정
  src/main/java/hana/event/controller/EventController.java
Labels: fix

#104 refactor: 거래내역 조회 캐싱 (#48)
  src/main/java/hana/account/controller/TransactionController.java
  src/main/java/hana/account/dto/DeptAccountInfoDto.java
  src/main/java/hana/account/dto/TransactionsReadResDto.java
  src/main/java/hana/account/dto/TransactionsRemitCreateReqDto.java
  src/main/java/hana/account/service/AccountService.java
  src/main/java/hana/account/service/TransactionService.java
Labels: refactor

#106 feat: 이벤트 선착 구현
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/domain/EventArrivalRepository.java
  src/main/java/hana/event/domain/EventWinnerRepository.java
  src/main/java/hana/event/domain/Fcfs.java
  src/main/java/hana/event/domain/FcfsEvent.java
  src/main/java/hana/event/dto/EventJoinResDto.java
  src/main/java/hana/event/exception/AlreadyEndEventException.java
  src/main/java/hana/event/exception/EventHttpCode.java
  src/main/java/hana/event/exception/NotStartEventException.java
  src/main/java/hana/event/service/EventService.java
Labels: feat

#109 feat: 학과 계좌 정보 조회 API (#107)
  src/main/java/hana/account/controller/TransactionController.java
  src/main/java/hana/account/service/TransactionService.java
  src/main/java/hana/college/controller/DeptController.java
  src/main/java/hana/college/dto/DeptInfoReadResDto.java
  src/main/java/hana/college/service/DeptService.java
Labels: feat

#116 refactor: 스토리 신청 Req 파람 대소문자 변경 (#115)
  src/main/java/hana/story/controller/StoryController.java
Labels: refactor, style

#118 스토리 목록, 금융상식 목록 조회 페이지네이션 기능 수정
  src/main/java/hana/knowledge/service/KnowledgeService.java
  src/main/java/hana/story/service/StoryCommentService.java
Labels: refactor

#120 feat: 알림 도메인 구현
  src/main/java/hana/common/Service/FCMService.java
  src/main/java/hana/common/config/SecurityConfig.java
  src/main/java/hana/common/dto/Notification/FcmSendReqDto.java
  src/main/java/hana/event/task/ScheduledEventTasks.java
  src/main/java/hana/member/controller/MemberController.java
  src/main/java/hana/member/domain/Notice.java
  src/main/java/hana/member/domain/NoticeRepository.java
  src/main/java/hana/member/dto/MemberCreateNoticeReqDto.java
  src/main/java/hana/member/dto/MemberCreateNoticeResDto.java
  src/main/java/hana/member/dto/MemberDeleteNoticeResDto.java
  src/main/java/hana/member/dto/MemberReadNoticesResDto.java
  src/main/java/hana/member/service/MemberService.java
  src/main/java/hana/notification/controller/NotificationController.java
  src/main/java/hana/notification/dto/NotificationTestDto.java
  src/main/resources/static/erd/erd.png
  src/main/resources/templates/index.html
Labels: feat

#124 fix: 스토리 댓글/좋아요 수 null리턴 수정 (#123)
  src/main/java/hana/story/domain/Story.java
Labels: fix

#126 fix: 스토리 이미지 null일 경우 로직 변경 (#125)
  src/main/java/hana/story/service/StoryService.java
Labels: fix, refactor

#128 fix: 거래내역 정렬 조건 추가(#127)
  src/main/java/hana/account/domain/TransactionRepositoryImpl.java
Labels: fix

#131 feat: 계좌 비밀번호 확인 API 생성 (#130)
  src/main/java/hana/account/controller/AccountController.java
  src/main/java/hana/account/dto/AccountPwCheckReqDto.java
  src/main/java/hana/account/dto/AccountPwCheckResDto.java
  src/main/java/hana/account/service/AccountService.java
Labels: feat

#133 hotfix: 학과 정보 조회 임의 처리
  src/main/java/hana/college/controller/DeptController.java
Labels: fix, refactor

#137 feat: 간편로그인과 영하나 접속 API 분리
  src/main/java/hana/event/task/ScheduledEventTasks.java
  src/main/java/hana/member/controller/MemberController.java
  src/main/java/hana/member/dto/MemberLoginResDto.java
  src/main/java/hana/member/dto/StudentLoginResDto.java
  src/main/java/hana/member/service/StudentService.java
Labels: feat

#136 학생증 조회 API DeptIdx, StudentIdx, MemberIdx, isAdmin 추가
  src/main/java/hana/member/dto/StudentReadResDto.java
  src/main/java/hana/member/service/StudentService.java
  src/main/java/hana/story/service/StoryService.java
Labels: refactor

#140 refactor: 이벤트 생성/수정/삭제 권한 추가
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/exception/EventCreateOnlyAdminException.java
  src/main/java/hana/event/exception/EventDeleteOnlyAdminException.java
  src/main/java/hana/event/exception/EventDeleteOnlyOwnerException.java
  src/main/java/hana/event/exception/EventHttpCode.java
  src/main/java/hana/event/exception/EventUpdateOnlyAdminException.java
  src/main/java/hana/member/domain/Student.java
  src/main/java/hana/member/service/StudentService.java
Labels: refactor

#141 fix: 학과 관련 입출금 로직 변경(#132)
  src/main/java/hana/account/controller/TransactionController.java
  src/main/java/hana/account/dto/TransactionsRemitCreateReqDto.java
  src/main/java/hana/account/service/AccountService.java
  src/main/java/hana/account/service/TransactionService.java
  src/main/java/hana/college/controller/DeptController.java
  src/main/java/hana/college/service/DeptService.java
Labels: fix, refactor

#142 fix: 더영하나 접속 DTO 수정
  src/main/java/hana/member/controller/MemberController.java
  src/main/java/hana/member/dto/StudentLoginResDto.java
Labels: fix

#144 docs: API 명세 추가
  src/main/java/hana/common/config/SecurityConfig.java
  src/main/resources/static/api/api.png
  src/main/resources/templates/index.html
Labels: docs

#145 refactor: 스토리 댓글 목록 조회 API 수정
  src/main/java/hana/member/domain/Student.java
  src/main/java/hana/story/domain/StoryCommentRepository.java
  src/main/java/hana/story/dto/StoryCommentPaginationDto.java
  src/main/java/hana/story/dto/StoryReadCommentsResDto.java
  src/main/java/hana/story/service/StoryCommentService.java
Labels: refactor

#149 fix: 타임존 한국으로 변경
  src/main/java/hana/reward/service/RewardService.java
Labels: fix

#153 fix: 이벤트 API DTO LocalDateTime -> String
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/dto/EventCreateReqDto.java
  src/main/java/hana/event/dto/EventUpdateReqDto.java
Labels: fix

#154 fix: 스토리 이미지 확장자 png, jpg 모두 가능하게 변경 (#151)
  src/main/java/hana/story/service/StoryService.java
Labels: fix

#155 fix: 이벤트 DTO에 DateTimeFormatter 적용
  src/main/java/hana/event/controller/EventController.java
Labels: fix

#160 refactor: 삭제된 글 스케줄러 안 돌게 수정
  src/main/java/hana/story/service/MatchCountScheduler.java
Labels: refactor

#164 refactor: 로그인 시점에 캐싱
  src/main/java/hana/common/config/JwtAuthenticationFilter.java
  src/main/java/hana/common/config/SecurityConfig.java
  src/main/java/hana/member/controller/MemberController.java
  src/main/java/hana/member/domain/MemberToken.java
  src/main/java/hana/member/domain/MemberTokenRepository.java
  src/main/java/hana/member/service/MemberTokenService.java
Labels: refactor
