Repository the-young-hana/theYoungHana-backend, pull requests merged in 2024-06, with the labels that each got.

#7 chore: 프로젝트 도메인 설정
  src/main/java/hana/account/controller/TransactionController.java
  src/main/java/hana/account/domain/Account.java
  src/main/java/hana/account/domain/AccountRepository.java
  src/main/java/hana/account/domain/Transaction.java
  src/main/java/hana/account/domain/TransactionRepository.java
  src/main/java/hana/account/domain/TransactionTypeEnumType.java
  src/main/java/hana/account/dto/TransactionsReadResDto.java
  src/main/java/hana/account/service/TransactionService.java
  src/main/java/hana/admin/controller/AdminController.java
  src/main/java/hana/admin/service/AdminService.java
  src/main/java/hana/college/domain/College.java
  src/main/java/hana/college/domain/CollegeRepository.java
  src/main/java/hana/college/domain/Dept.java
  src/main/java/hana/college/domain/DeptRepository.java
  src/main/java/hana/common/config/SwaggerConfig.java
  src/main/java/hana/common/entity/BaseEntity.java
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/domain/Event.java
  src/main/java/hana/event/domain/EventEnumType.java
  src/main/java/hana/event/domain/EventPrize.java
  src/main/java/hana/event/domain/EventPrizeRepository.java
  src/main/java/hana/event/domain/EventRepository.java
  src/main/java/hana/event/domain/EventWinner.java
  src/main/java/hana/event/domain/EventWinnerRepository.java
  src/main/java/hana/event/service/EventService.java
  src/main/java/hana/knowledge/controller/KnowledgeController.java
  src/main/java/hana/knowledge/domain/Knowledge.java
  src/main/java/hana/knowledge/domain/KnowledgeRepository.java
  src/main/java/hana/knowledge/service/KnowledgeService.java
  src/main/java/hana/member/controller/StudentController.java
  src/main/java/hana/member/domain/Notice.java
  src/main/java/hana/member/domain/NoticeRepository.java
  src/main/java/hana/member/domain/RewardCategoryEnumType.java
  src/main/java/hana/member/domain/RewardHistory.java
  src/main/java/hana/member/domain/Student.java
  src/main/java/hana/member/domain/StudentRepository.java
  src/main/java/hana/member/domain/StudentStatusEnumType.java
  src/main/java/hana/member/dto/MemberLoginResDto.java
  src/main/java/hana/member/dto/StudentQrReadResDto.java
  src/main/java/hana/member/dto/StudentReadResDto.java
  src/main/java/hana/member/service/MemberService.java
  src/main/java/hana/member/service/StudentService.java
  src/main/java/hana/reward/domain/Quiz.java
  src/main/java/hana/reward/domain/QuizRepository.java
  src/main/java/hana/story/controller/StoryController.java
  src/main/java/hana/story/domain/Story.java
  src/main/java/hana/story/domain/StoryComment.java
  src/main/java/hana/story/domain/StoryCommentRepository.java
  src/main/java/hana/story/domain/StoryRepository.java
  src/main/java/hana/story/domain/TransactionDetail.java
  src/main/java/hana/story/domain/TransactionDetailRepository.java
  src/main/java/hana/story/service/StoryService.java
  src/main/java/hana/transaction/dto/TransactionsReadResDto.java
  src/main/resources/application.yml
Labels: chore

#12 refactor: 회원 간편로그인 수정 (deptIdx 추가)
  src/main/java/hana/common/annotation/AuthenticatedMember.java
  src/main/java/hana/common/config/JwtAuthenticationFilter.java
  src/main/java/hana/common/config/JwtTokenProvider.java
  src/main/java/hana/common/config/SecurityConfig.java
  src/main/java/hana/common/config/SwaggerConfig.java
  src/main/java/hana/common/dto/JwtToken.java
  src/main/java/hana/common/dto/UserDetails.java
  src/main/java/hana/common/utils/JwtUtils.java
  src/main/java/hana/member/controller/MemberController.java
  src/main/java/hana/member/domain/Student.java
  src/main/java/hana/member/domain/StudentRepository.java
  src/main/java/hana/member/service/MemberService.java
  src/main/java/hana/member/service/StudentService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/templates/index.html
Labels: refactor

#13 feat: 금융상식 목록 조회 구현
  src/main/java/hana/knowledge/controller/KnowledgeController.java
  src/main/java/hana/knowledge/service/KnowledgeService.java
Labels: feat

#18 feat: 이벤트 목록 조회 구현
  .github/workflows/pull_request_test.yml
  src/main/java/hana/account/controller/TransactionController.java
  src/main/java/hana/common/annotation/AuthenticatedMember.java
  src/main/java/hana/common/config/JwtAuthenticationFilter.java
  src/main/java/hana/common/config/JwtTokenProvider.java
  src/main/java/hana/common/exception/CommonHttpCode.java
  src/main/java/hana/common/exception/TokenExpiredException.java
  src/main/java/hana/common/exception/TokenHasUnknownMemberException.java
  src/main/java/hana/common/utils/JwtUtils.java
  src/main/java/hana/common/vo/JwtToken.java
  src/main/java/hana/common/vo/UserDetails.java
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/domain/EventRepository.java
  src/main/java/hana/event/service/EventService.java
  src/main/java/hana/member/controller/MemberController.java
  src/main/java/hana/member/domain/StudentRepository.java
  src/main/java/hana/member/exception/MemberHttpCode.java
  src/main/java/hana/member/exception/UnlistedMemberException.java
  src/main/java/hana/member/service/MemberService.java
  src/main/java/hana/story/controller/StoryController.java
Labels: feat

#20 feat: 금융 퀴즈 api 구현
  build.gradle
  src/main/java/hana/college/domain/DeptRepository.java
  src/main/java/hana/reward/controller/RewardController.java
  src/main/java/hana/reward/domain/Quiz.java
  src/main/java/hana/reward/dto/RewardAnswerQuizResDto.java
  src/main/java/hana/reward/service/RewardService.java
Labels: feat

#24 feat: 금융상식 상세 정보 조회
  src/main/java/hana/event/domain/Event.java
  src/main/java/hana/knowledge/controller/KnowledgeController.java
  src/main/java/hana/knowledge/domain/Knowledge.java
  src/main/java/hana/knowledge/exception/KnowledgeHttpCode.java
  src/main/java/hana/knowledge/exception/UnlistedKnowledgeException.java
  src/main/java/hana/knowledge/service/KnowledgeService.java
  src/main/resources/data.sql
Labels: feat

#27 chore: Aws s3 연결
  build.gradle
  lombok.config
  src/main/java/hana/common/config/S3Config.java
  src/main/java/hana/common/utils/ImageUtils.java
  src/main/java/hana/reward/controller/RewardController.java
  src/main/resources/application.yml
Labels: chore

#32 feat: 이벤트 상세조회 구현
  build.gradle
  src/main/java/hana/common/config/JwtAuthenticationFilter.java
  src/main/java/hana/common/utils/ImageUtils.java
  src/main/java/hana/common/utils/JsonUtils.java
  src/main/java/hana/common/utils/JwtUtils.java
  src/main/java/hana/event/controller/EventController.java
  src/main/java/hana/event/domain/Event.java
  src/main/java/hana/event/domain/EventRepository.java
  src/main/java/hana/event/dto/EventReadResDto.java
  src/main/java/hana/event/exception/EventHttpCode.java
  src/main/java/hana/event/exception/UnavailableEventException.java
  src/main/java/hana/event/service/EventService.java
  src/main/resources/application.yml
  src/test/java/hana/common/config/AppTestConfig.java
Labels: feat

#34 feat: 학생증 관련 API 구현
  build.gradle
  src/main/java/hana/common/utils/RandomStringGenerator.java
  src/main/java/hana/member/controller/StudentController.java
  src/main/java/hana/member/domain/Student.java
  src/main/java/hana/member/dto/StudentReadResDto.java
  src/main/java/hana/member/exception/StudentHttpCode.java
  src/main/java/hana/member/exception/StudentNotFoundException.java
  src/main/java/hana/member/service/StudentService.java
Labels: feat

#38 refactor: 스토리 컨트롤러 : 스토리, 스토리 댓글 분리(#37)
  src/main/java/hana/story/controller/StoryCommentController.java
  src/main/java/hana/story/controller/StoryController.java
Labels: refactor

#40 fix: s3등록 및 삭제 방식 변경 (#39)
  src/main/java/hana/common/utils/ImageUtils.java
Labels: chore, fix

#41 feat: 스토리 수정/삭제 구현 (#26)
  src/main/java/hana/common/entity/BaseEntity.java
  src/main/java/hana/story/controller/StoryController.java
  src/main/java/hana/story/domain/Story.java
  src/main/java/hana/story/domain/TransactionDetailRepository.java
  src/main/java/hana/story/dto/StoryDeleteResDto.java
  src/main/java/hana/story/dto/StoryUpdateReqDto.java
  src/main/java/hana/story/dto/StoryUpdateResDto.java
  src/main/java/hana/story/service/StoryService.java
  src/main/java/hana/story/service/TransactionDetailService.java
Labels: feat

#42 style: 병합 충돌 수정(spotlessApply)
  src/main/java/hana/story/controller/StoryController.java
Labels: style

#46 chore: fcm 연동
  .github/workflows/ci_and_cd.yml
  .gitignore
  build.gradle
  src/main/generated/hana/account/domain/QAccount.java
  src/main/generated/hana/account/domain/QTransaction.java
  src/main/generated/hana/college/domain/QCollege.java
  src/main/generated/hana/college/domain/QDept.java
  src/main/generated/hana/common/entity/QBaseEntity.java
  src/main/generated/hana/common/entity/QBaseTimeEntity.java
  src/main/generated/hana/event/domain/QEvent.java
  src/main/generated/hana/event/domain/QEventPrize.java
  src/main/generated/hana/event/domain/QEventWinner.java
  src/main/generated/hana/knowledge/domain/QKnowledge.java
  src/main/generated/hana/member/domain/QMember.java
  src/main/generated/hana/member/domain/QNotice.java
  src/main/generated/hana/member/domain/QRewardHistory.java
  src/main/generated/hana/member/domain/QStudent.java
  src/main/generated/hana/member/domain/QStudentCard.java
  src/main/generated/hana/reward/domain/QQuiz.java
  src/main/generated/hana/story/domain/QStory.java
  src/main/generated/hana/story/domain/QStoryComment.java
  src/main/generated/hana/story/domain/QTransactionDetail.java
  src/main/java/hana/common/Service/FCMService.java
  src/main/java/hana/common/config/FirebaseConfig.java
  src/main/java/hana/common/dto/Notification/FcmMessageResDto.java
  src/main/java/hana/common/dto/Notification/FcmSendReqDto.java
  src/main/java/hana/notification/controller/NotificationController.java
  src/main/java/hana/notification/dto/NotificationTestDto.java
  src/main/resources/application.yml
Labels: chore

#47 fix: 배포 오류 수정
  .github/workflows/pull_request_test.yml
  src/test/java/hana/common/config/AppTestConfig.java
Labels: fix
